# Generated by Django 5.2.12 on 2026-05-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_add_share_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionPost',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'collection_items',
                'ordering': ['-added_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HiddenPost',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hidden_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostNote',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'post_notes',
                'ordering': ['-updated_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('user', 'User'), ('message', 'Message')], max_length=20)),
                ('target_id', models.CharField(max_length=26)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate_content', 'Inappropriate Content'), ('harassment', 'Harassment'), ('misinformation', 'Misinformation'), ('copyright', 'Copyright Violation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
