# Generated by Django 5.2.12 on 2026-05-17 05:00

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_id, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('locked', 'Locked'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=20)),
                ('auth_provider', models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('facebook', 'Facebook')], default='local', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_id, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='UserLockLog',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_id, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('lock_type', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], default='temporary', max_length=20)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(db_column='locked_by_id', on_delete=django.db.models.deletion.RESTRICT, related_name='created_lock_logs', to=settings.AUTH_USER_MODEL)),
                ('unlocked_by', models.ForeignKey(blank=True, db_column='unlocked_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_lock_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='lock_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lock_logs',
                'ordering': ['-locked_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_id, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('learning_field', models.CharField(blank=True, max_length=100, null=True)),
                ('interests', models.JSONField(blank=True, null=True)),
                ('preferred_language', models.CharField(default='vi', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_topics', models.ManyToManyField(blank=True, db_table='users_userprofile_favorite_topics', related_name='favorited_by_profiles', to='content.topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_id, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('notify_likes', models.BooleanField(default=True)),
                ('notify_comments', models.BooleanField(default=True)),
                ('notify_follows', models.BooleanField(default=True)),
                ('notify_messages', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only'), ('private', 'Private')], default='public', max_length=30)),
                ('allow_messages_from', models.CharField(choices=[('everyone', 'Everyone'), ('followers_only', 'Followers Only'), ('nobody', 'Nobody')], default='everyone', max_length=30)),
                ('autoplay_audio', models.BooleanField(default=True)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='dark', max_length=20)),
                ('language_code', models.CharField(default='vi', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='UserTagPreference',
            fields=[
                ('id', models.CharField(default=apps.users.models.generate_id, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='content.tag')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='tag_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tag_preferences',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
