# Generated by Django 5.2.12 on 2026-03-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('category_id', models.CharField(blank=True, max_length=26, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('dialogue_script', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('uploaded_document', 'Uploaded Document'), ('ai_generated', 'AI Generated')], default='manual', max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('language_code', models.CharField(default='vi', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='private', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed'), ('archived', 'Archived'), ('hidden', 'Hidden')], default='draft', max_length=20)),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('learning_field', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_url', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('listen_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('save_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostAudioVersion',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('voice_name', models.CharField(max_length=100)),
                ('format', models.CharField(default='mp3', max_length=20)),
                ('bitrate_kbps', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('audio_url', models.CharField(max_length=500)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'post_audio_versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('document_url', models.CharField(max_length=500)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'post_documents',
                'managed': False,
            },
        ),
    ]
